- GOTS
- Organic 100 Content Standard
- ECOCERT Textile
- bioRE
- OEKO-TEX Standard 100
- ZDHC
- bluesign
- Recycled 100 Claim Standard
- Global Recycled Standard
- OEKO-TEX Made in Green
- Fairtrade COTTON
- BCI (Better Cotton Initiative)
- EU Ecolabel

